apiVersion: v1
kind: Service
metadata:
  name: ingredient-api-svc
  labels:
    app: ingredient-api
    commit: "1"
spec:
  ports:
  - port: 30000
    targetPort: 3050
  selector:
    app: ingredient-api
    commit: "1"
  type: LoadBalancer
---
